version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "teslabot-fb-sharhad"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1b6n59ysf8mzf"
s3_prefix = "teslabot-fb-sharhad"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["SentimentFunction=473918350307.dkr.ecr.us-east-1.amazonaws.com/teslabotfbsharhad2bcea6cf/sentimentfunction35d37012repo"]
